### ISSUE TITLE
Divergence with Wolfram Mathematica

### ISSUE THREAD

**Issue by ZupoLlask** [tfm000/sklarpy#18]
Dear Tyler,

Do you know about divergences with Wolfram Mathematica, for the same distributions/parameters and data?

I'm comparing implementations and getting very different results for the same data. But I'm still trying to figure it out...

**Comment by tfm000** [comment]
Hi, what functions/distributions are you referring to?

**Comment by ZupoLlask** [comment]
I'll create a minimal case to illustrate the issue and to make it easier to narrow it down.

I stumbled upon this issue while trying to replicate in Python what I have in Mathematica...

I'll come back to you tomorrow.

Thanks.

**Comment by ZupoLlask** [comment]
Dear Tyler,

I'm glad to let you know that sklarpy is performing wonderfully when comparing with Wolfram Mathematica.

It was my mistake when calculating probabilities!

Sorry for the worrying you. :-)
